GAME_TITLE = "AddVenture Army"

GAME_WINDOW_WIDTH = 800
GAME_WINDOW_HEIGHT = 800

GAME_FPS = 60

PLAYER_WIDTH = 16
PLAYER_HEIGHT = 24
PLAYER_SPEED = 5
PLAYER_SCALE = 3

BONUS_WIDTH = 300
BONUS_HEIGHT = 50
BONUS_SPEED = 3
BONUS_POSITION_LEFT = 0
BONUS_POSITION_RIGHT = 1
BONUS_OFFSET = 30

