GAME_TITLE = "AddVenture Army"

GAME_WINDOW_WIDTH = 800
GAME_WINDOW_HEIGHT = 800

GAME_FPS = 60

PLAYER_WIDTH = 100
PLAYER_HEIGHT = 100
PLAYER_SPEED = 5

ENEMY_WIDTH = 300
ENEMY_HEIGHT = 50
ENEMY_SPEED = 2
ENEMY_POSITION_LEFT = 0
ENEMY_POSITION_RIGHT = 1
ENEMY_OFFSET = 20

